version: '3.9'

services:
  discovery-service:
    build: ./discovery-service
    ports:
      - "8761:8761"
    networks:
      - spring-net
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
#      interval: 30s
#      timeout: 10s
#      retries: 5

  config-service:
    build:
      context: .
      dockerfile: config-service/Dockerfile
    ports:
      - "9999:9999"
#    depends_on:
#      discovery-service:
#        condition: service_healthy
    networks:
      - spring-net
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:9999/actuator/health"]
#      interval: 30s
#      timeout: 10s
#      retries: 5

  gateway-service:
    build:
      context: .
      dockerfile: gateway-service/Dockerfile
    ports:
      - "8888:8888"
#    depends_on:
#      discovery-service:
#        condition: service_healthy
#      config-service:
#        condition: service_healthy
    networks:
      - spring-net

#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
#      interval: 30s
#      timeout: 10s
#      retries: 5

  authorization-service:
    build: ./authorization-service
    ports:
      - "8084:8084"
#    depends_on:
#      discovery-service:
#        condition: service_healthy
#      config-service:
#        condition: service_healthy
    networks:
      - spring-net
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:8084/actuator/health"]
#      interval: 30s
#      timeout: 10s
#      retries: 5

  order-service:
    build: ./order-service
    ports:
      - "8083:8083"
#      discovery-service:
#        condition: service_healthy
#      config-service:
#        condition: service_healthy
#      gateway-service:
#        condition: service_healthy
    networks:
      - spring-net
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:8083/actuator/health"]
#      interval: 30s
#      timeout: 10s
#      retries: 5

  customer-service:
    build: ./customer-service
    ports:
      - "8081:8081"
#      discovery-service:
#        condition: service_healthy
#      config-service:
#        condition: service_healthy
#      gateway-service:
#        condition: service_healthy
    networks:
      - spring-net
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
#      interval: 30s
#      timeout: 10s
#      retries: 5

  product-service:
    build:
      context: .
      dockerfile: product-service/Dockerfile
    ports:
      - "8082:8082"
#      discovery-service:
#        condition: service_healthy
#      config-service:
#        condition: service_healthy
#      gateway-service:
#        condition: service_healthy
    networks:
      - spring-net
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
#      interval: 30s
#      timeout: 10s
#      retries: 5

#  vault-service:
#    build: ./vault-service
#    ports:
#      - "8200:8200"
#    environment:
#      VAULT_DEV_ROOT_TOKEN_ID: root
#      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
#    cap_add:
#      - IPC_LOCK
#    networks:
#      - spring-net
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:8200/v1/sys/health"]
#      interval: 30s
#      timeout: 10s
#      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    command: start-dev
    environment:
      KEYCLOAK_ADMIN : "admin"
      KEYCLOAK_ADMIN_PASSWORD : "admin"
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/conf/server.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/conf/server.key
    ports:
      - "7080:8080"
      - "8443:8443"
    networks:
      - spring-net
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./keyssh/server.crt:/opt/keycloak/conf/server.crt
      - ./keyssh/server.key:/opt/keycloak/conf/server.key

networks:
  spring-net:
    driver: bridge

volumes:
  keycloak_data: