spring:
  application:
    name: authorization-service
  cloud:
    config:
      enabled: true
    discovery:
      enabled: true
    gateway:
      enabled: true
  config:
        #import: optional:configserver:http://localhost:9999
    import: optional:configserver:http://config-service:9999
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:authorization-db
    username: authorization-service
  security:
    oauth2:
      resourceserver:
        jwt:
          #issuer-uri: http://localhost:7080/realms/buyme-realm
          #jwk-set-uri: http://localhost:7080/realms/buyme-realm/protocol/openid-connect/certs
          issuer-uri: https://keycloak:8443/realms/buyme-realm
          jwk-set-uri: https://keycloak:8443/realms/buyme-realm/protocol/openid-connect/certs
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka

server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: "*"