# =======================================================================
## Spring
# =======================================================================
spring:
  application:
    name: gateway-service
  cloud:
    config:
      enabled: false
    discovery:
      enabled: true
#    gateway:
#      routes:
#        - id: r1
#          uri: http://localhost:8081/
#          predicates:
#            - Path=/customers/**
#        - id: r2
#          uri: http://localhost:8082/
#          predicates:
#            - Path=/api/products/**
#            #- Method=GET
  security:
    oauth2:
      resourceserver:
        jwt:
          #issuer-uri: http://localhost:7080/realms/buyme-realm
          #jwk-set-uri: http://localhost:7080/realms/buyme-realm/protocol/openid-connect/certs
          issuer-uri: http://keycloak:9090/realms/buyme-realm
          jwk-set-uri: http://keycloak:9090/realms/buyme-realm/protocol/openid-connect/certs
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka

server:
  port: 8888