spring:
  profiles:
    active: native
  config:
    name: configserver
  application:
    name: config-service
  cloud:
    config:
      server:
        native:
          search-locations: file:///app/config/
          #search-locations: file:///D:\Dev\Ici\buyme-advanced-ms-architecture-main\config-repo-main
server:
  port: 9999